function [ w ] = getFisher( X1, X2 )
% Given two set of data, find a vector that could best separate the points
% generated by projecting the data onto this vector according to Fisher
% Linear Discrimination formula
%       
%       Input:
%           X1: Class 1 data, each column is a data 
%           X2: Class 2 data, each column is a data
%       Output:
%           fisher: vector that could maximum the J(w)

% Compute the matrix C
X1 = double(X1);
X2 = double(X2);
me1 = mean(X1, 2);
me2 = mean(X2, 2);
C = [X1 - repmat(me1, 1, size(X1, 2)), X2 - repmat(me2, 1, size(X2, 2))];
C = C(:, randperm(size(C, 2)));

% Compute the matrix B
B = C'*C;

% Compute the eigenvalues and enignvectors of B
[V, D] = eig(B);

% Normalize each eigenvalues
for i = 1:size(V, 2)
    V(:, i) = V(:, i) / norm(V(:, i));
end

% Compute the matrix A
A = [];
for i = 1 : size(C, 2)
%     col = (sqrt(D(i, i)) / norm(C*V(:, i)))*C*V(:, i);
    col = sqrt(D(i, i)) * C * V(:, i);
    A = [A, col];
end

% Compute y vector
m1 = mean(X1, 2);
m2 = mean(X2, 2);

y = A'*(m1 - m2);

% Compute the final w
z = inv(D*D*V')*y;
w = C*z;
w = w/norm(w);
end

